package org.crimsoncode2026.domain.usecases

import org.crimsoncode2026.data.BroadcastType
import org.crimsoncode2026.data.Category
import org.crimsoncode2026.data.Event
import org.crimsoncode2026.data.Severity

/**
 * Result of creating an event
 */
sealed class CreateEventResult {
    data class Success(
        val event: Event,
        val recipients: List<org.crimsoncode2026.data.EventRecipient> = emptyList()
    ) : CreateEventResult()

    data class Error(val message: String) : CreateEventResult()
}

/**
 * Parameters for creating a new event
 */
data class CreateEventParams(
    val severity: Severity,
    val category: Category,
    val lat: Double,
    val lon: Double,
    val locationOverride: String? = null,
    val description: String,
    val isPublic: Boolean = true,
    val selectedContactIds: List<String> = emptyList()
)

/**
 * Create Event Use Case
 *
 * Unified use case for creating both public and private events.
 * Validates required fields, sets expiration, handles broadcast type logic.
 * Delegates to CreatePublicEventUseCase and CreatePrivateEventWithRecipientsUseCase.
 *
 * Spec requirements:
 * - Public events: broadcastType=PUBLIC, isAnonymous=true
 * - Private events: broadcastType=PRIVATE, requires selected contacts
 * - Events expire after 48 hours
 * - Private events create EventRecipient records for each matched contact
 *
 * @param createPublicEventUseCase Use case for public event creation
 * @param createPrivateEventWithRecipientsUseCase Use case for private event with recipients
 */
class CreateEventUseCase(
    private val createPublicEventUseCase: CreatePublicEventUseCase,
    private val createPrivateEventWithRecipientsUseCase: CreatePrivateEventWithRecipientsUseCase
) {

    /**
     * Create an event based on broadcast type
     *
     * @param params Event creation parameters
     * @return CreateEventResult with created event/recipients or error
     */
    suspend operator fun invoke(params: CreateEventParams): CreateEventResult {
        // Step 1: Validate required fields
        val validationError = validateParams(params)
        if (validationError != null) {
            return CreateEventResult.Error(validationError)
        }

        // Step 2: Create base event object
        val now = System.currentTimeMillis()
        val event = Event(
            id = "", // Will be generated by repository
            creatorId = "", // Will be set by delegated use case
            severity = params.severity.value,
            category = params.category.value,
            lat = params.lat,
            lon = params.lon,
            locationOverride = params.locationOverride,
            broadcastType = if (params.isPublic) {
                BroadcastType.PUBLIC.value
            } else {
                BroadcastType.PRIVATE.value
            },
            description = params.description,
            isAnonymous = params.isPublic, // Public events are anonymous
            createdAt = now,
            expiresAt = now + Event.DEFAULT_EXPIRATION_MS
        )

        // Step 3: Route to appropriate use case based on broadcast type
        return if (params.isPublic) {
            // Public event creation
            when (val result = createPublicEventUseCase(event)) {
                is CreatePublicEventResult.Success -> {
                    CreateEventResult.Success(
                        event = result.event,
                        recipients = emptyList()
                    )
                }
                is CreatePublicEventResult.Error -> {
                    CreateEventResult.Error(result.message)
                }
            }
        } else {
            // Private event creation with recipients
            when (val result = createPrivateEventWithRecipientsUseCase(
                event = event,
                selectedContactIds = params.selectedContactIds
            )) {
                is CreatePrivateEventWithRecipientsResult.Success -> {
                    CreateEventResult.Success(
                        event = result.event,
                        recipients = result.recipients
                    )
                }
                is CreatePrivateEventWithRecipientsResult.Error -> {
                    CreateEventResult.Error(result.message)
                }
            }
        }
    }

    /**
     * Validate event creation parameters
     *
     * @param params Parameters to validate
     * @return Error message if invalid, null if valid
     */
    private fun validateParams(params: CreateEventParams): String? {
        // Validate latitude (-90 to 90)
        if (params.lat < -90.0 || params.lat > 90.0) {
            return "Invalid latitude. Must be between -90 and 90"
        }

        // Validate longitude (-180 to 180)
        if (params.lon < -180.0 || params.lon > 180.0) {
            return "Invalid longitude. Must be between -180 and 180"
        }

        // Validate description length (max 500 characters per spec)
        if (params.description.length > 500) {
            return "Description too long. Maximum 500 characters"
        }

        // Validate description not empty
        if (params.description.isBlank()) {
            return "Description is required"
        }

        // Validate private events have selected contacts
        if (!params.isPublic && params.selectedContactIds.isEmpty()) {
            return "Private events require at least one selected contact"
        }

        return null
    }

    /**
     * Create a public event (convenience method)
     *
     * @param params Event creation parameters with isPublic=true
     * @return CreateEventResult with created event or error
     */
    suspend fun createPublic(params: CreateEventParams): CreateEventResult {
        return invoke(params.copy(isPublic = true))
    }

    /**
     * Create a private event (convenience method)
     *
     * @param params Event creation parameters with isPublic=false
     * @return CreateEventResult with created event and recipients or error
     */
    suspend fun createPrivate(params: CreateEventParams): CreateEventResult {
        return invoke(params.copy(isPublic = false))
    }
}
